const AUDIT_TYPES = {
  WEEKEND_STAGE_TRANSITION: 'WEEKEND_STAGE_TRANSITION',
  SETUP_CHANGED: 'SETUP_CHANGED',
  NOTE_ADDED: 'NOTE_ADDED',
  COMMENT_ADDED: 'COMMENT_ADDED',
}

module.exports = { AUDIT_TYPES }