const QUALIFYING_SEGMENTS = {
    NULL: null,
    Q1: 'Q1',
    Q2: 'Q2',
    Q3: 'Q3'
}

const QUALIFYING_SEGMENTS_ORDER = [
    QUALIFYING_SEGMENTS.NULL,
    QUALIFYING_SEGMENTS.Q1,
    QUALIFYING_SEGMENTS.Q2,
    QUALIFYING_SEGMENTS.Q3,
]

const PRACTICE_SEGMENTS = {
    NULL: null,
    P1: 'P1',
    P2: 'P2',
    P3: 'P3'
}

const PRACTICE_SEGMENTS_ORDER = [
    PRACTICE_SEGMENTS.NULL,
    PRACTICE_SEGMENTS.P1,
    PRACTICE_SEGMENTS.P2,
    PRACTICE_SEGMENTS.P3,
]

module.exports = { QUALIFYING_SEGMENTS, QUALIFYING_SEGMENTS_ORDER, PRACTICE_SEGMENTS, PRACTICE_SEGMENTS_ORDER }
